### ISSUE TITLE
Feature request: Inserting envelope into displayed GeoJSON

### ISSUE THREAD

**Issue by ehx-v1** [JasonSanford/geojsonlint.com#22]
Hi, I'd like to be able to drag an envelope over the displayed data, and to see its vertices when doing so. The reason is that I'm using GeoJSONLint for debugging test cases for geospatial queries and would like to use this to determine the search window that should give me the desired test data if my queries are working.

**Comment by JasonSanford** [comment]
I'm not sure that this would fit well into this utility, but it's something that http://bboxfinder.com/ should work well for.
