### ISSUE TITLE
Link to GeoJSON spec link needs an update

### ISSUE THREAD

**Issue by arcvancouver** [JasonSanford/geojsonlint.com#25]
Hi! Heard about the site, and checked it out.  Where it says "Use this site to validate and view your GeoJSON. For details about GeoJSON, read the spec."... 

the link goes to the old 2008 spec. The new one (Aug 2016) is out now, and should point to here (RFC 7946):  https://tools.ietf.org/html/rfc7946

Cheers
CS

**Comment by JasonSanford** [comment]
Fixed. Thanks!
