### ISSUE TITLE
Put a link on geojsonlint.com pointing back here, or at least some contact info

### ISSUE THREAD

**Issue by jidanni** [JasonSanford/geojsonlint.com#28]
Is this the source repository for http://geojsonlint.com/ as mentioned in
https://github.com/ropensci/geojsonlint/issues/16#issuecomment-369486256 ?

If so, please add a link on http://geojsonlint.com/ pointing back here, as currently on http://geojsonlint.com/ there is no way listed to contact you. Thus people will file issues in https://github.com/ropensci/geojsonlint/issues/ etc. which see. Thanks.

**Comment by JasonSanford** [comment]
This is no longer the source for the app running at https://geojsonlint.com
