### ISSUE TITLE
https://geojsonlint.com/ - OpenStreetMap data is used for map but attribution is missing

### ISSUE THREAD

**Issue by matkoniecz** [JasonSanford/geojsonlint.com#33]
Hello,

As an OpenStreetMap contributor, I am pleased to see that you are using OpenStreetMap on your website.

However, I noticed that the map seems to lack the proper credit. OpenStreetMap's license requires that you both credit OpenStreetMap and make users aware of the data license. For more information, see: https://www.openstreetmap.org/copyright

Mapbox is hosting data and probably made this specific map style, including their logo is OK (and may be required by their ToC) but it is not attributing OpenStreetMap at all and is not fulfilling requirement to attribute source of data.

Initial view on loading the website:

![screen01](https://user-images.githubusercontent.com/899988/108696397-c4141680-7501-11eb-9bad-1c67f5f58018.png)

**Comment by JasonSanford** [comment]
Hi there. The geojsonlint.com domain is owned by someone else now. I think they forked this code and are running their own copy of it there. I added a note in the readme about this [here](a986fce113157d2d7ff94bf9a63057fba153b023).

**Comment by matkoniecz** [comment]
Thanks for the info! Though I would say that technically it is still a bug in code from this repository.

**Comment by JasonSanford** [comment]
I'd welcome a pull request to fix this bug.

**Comment by matkoniecz** [comment]
Would it be OK to simply modify .html file like https://github.com/JasonSanford/geojsonlint.com/pull/32/files did?
